import { TableData } from '../../types/TableData';

export const tableData:TableData = {
    rows: [
      {
        id: 1,
        title: 'Gassing Test',
        isTitleDisale: true,
        values: [
          {id: 1, value: '', elementType: 'numeric', isEditable: true},
          {id: 2, value: '1', elementType: 'numeric', isEditable: true},
          {id: 3, value: '2', elementType: 'numeric', isEditable: true},
          {id: 4, value: '3', elementType: 'numeric', isEditable: true},
          {id: 5, value: '4', elementType: 'numeric', isEditable: true},
          {id: 6, value: '5', elementType: 'numeric', isEditable: true},
          {id: 7, value: '6', elementType: 'numeric', isEditable: true},
          {id: 8, value: '7', elementType: 'numeric', isEditable: true},
          {id: 9, value: '8', elementType: 'numeric', isEditable: true},
        ],
      },
      {
        id: 2,
        title: 'Product',
        isTitleDisale: true,
        values: [
          {id: 1, value: 'TS60GA', elementType: 'default', isEditable: true},
          {id: 2, value: '', elementType: 'numeric', isEditable: true},
          {id: 3, value: '', elementType: 'numeric', isEditable: true},
          {id: 4, value: '', elementType: 'numeric', isEditable: true},
          {id: 5, value: '', elementType: 'numeric', isEditable: true},
          {id: 6, value: '', elementType: 'numeric', isEditable: true},
          {id: 7, value: '', elementType: 'numeric', isEditable: true},
          {id: 8, value: '', elementType: 'numeric', isEditable: true},
          {id: 9, value: '', elementType: 'numeric', isEditable: true},
        ],
      },
      {
        id: 3,
        title: 'Target Density (g/cc)',
        isTitleDisale: true,
        values: [
          {id: 1, value: '0', elementType: 'numeric', isEditable: true},
          {id: 2, value: '0', elementType: 'numeric', isEditable: true},
          {id: 3, value: '0', elementType: 'numeric', isEditable: true},
          {id: 4, value: '0', elementType: 'numeric', isEditable: true},
          {id: 5, value: '0', elementType: 'numeric', isEditable: true},
          {id: 6, value: '0', elementType: 'numeric', isEditable: true},
          {id: 7, value: '0', elementType: 'numeric', isEditable: true},
          {id: 8, value: '0', elementType: 'numeric', isEditable: true},
          {id: 9, value: '0', elementType: 'numeric', isEditable: true},
        ],
      },
      {
        id: 4,
        title: 'Cup Type (g)',
        isTitleDisale: true,
        values: [
          {id: 1, value: '', elementType: 'numeric', isEditable: true},
          {id: 2, value: '', elementType: 'numeric', isEditable: true},
          {id: 3, value: '', elementType: 'numeric', isEditable: true},
          {id: 4, value: '', elementType: 'numeric', isEditable: true},
          {id: 5, value: '', elementType: 'numeric', isEditable: true},
          {id: 6, value: '', elementType: 'numeric', isEditable: true},
          {id: 7, value: '', elementType: 'numeric', isEditable: true},
          {id: 8, value: '', elementType: 'numeric', isEditable: true},
          {id: 9, value: '', elementType: 'numeric', isEditable: true},
        ],
      },
      {
        id: 5,
        title: 'Hole Number',
        isTitleDisale: true,
        values: [
          {id: 1, value: '', elementType: 'numeric', isEditable: true},
          {id: 2, value: '', elementType: 'numeric', isEditable: true},
          {id: 3, value: '', elementType: 'numeric', isEditable: true},
          {id: 4, value: '', elementType: 'numeric', isEditable: true},
          {id: 5, value: '', elementType: 'numeric', isEditable: true},
          {id: 6, value: '', elementType: 'numeric', isEditable: true},
          {id: 7, value: '', elementType: 'numeric', isEditable: true},
          {id: 8, value: '', elementType: 'numeric', isEditable: true},
          {id: 9, value: '', elementType: 'numeric', isEditable: true},
        ],
      },
      {
        id: 6,
        title: 'Dischage Rate (km/min)',
        isTitleDisale: true,
        values: [
          {id: 1, value: '', elementType: 'numeric', isEditable: true},
          {id: 2, value: '', elementType: 'numeric', isEditable: true},
          {id: 3, value: '', elementType: 'numeric', isEditable: true},
          {id: 4, value: '', elementType: 'numeric', isEditable: true},
          {id: 5, value: '', elementType: 'numeric', isEditable: true},
          {id: 6, value: '', elementType: 'numeric', isEditable: true},
          {id: 7, value: '', elementType: 'numeric', isEditable: true},
          {id: 8, value: '', elementType: 'numeric', isEditable: true},
          {id: 9, value: '', elementType: 'numeric', isEditable: true},
        ],
      },
    ]};
